architecture:
    down_sample_rate: 1,4,4,4,4
    auxiliary_rate:  32,32,32,32,32
    channels: 32,64,128,128,256,256
    train_iter: 2
    test_iter: 2
    channel_ratio: 1
dataset:
    name: scannetv2 # [s3dis, scannetv2]
    loader: pn2 # [pn2]
    num_classes: 21 # s3dis: 13; scannetv2: 21
    input_feat: prgn # P: global xyz; p: xyz; n: normal; c: curvature; gn: groundtruth normal; r: rgb
    val_area: 5 # not used in scannetv2
    color_drop: 0.4
    num_points: 4096